### ISSUE TITLE
Implement libp2p Transport interface

### ISSUE THREAD

**Issue by bigs** [cretz/bine#1]
Leaving this here for future discussion. If you're up to receiving the patch, I might hash this out sometime soon or after the new `Transport` definition lands. `libp2p` aims to be a generally-useful networking library and having a tor transport would be a boon! The process could also simplify bine usage 😄

**Comment by cretz** [comment]
@bigs - While I'm up for receiving the patch, I would prefer it in a separate dir since the general use of this lib is unrelated to ipfs and I wouldn't want a dep on go-multiaddr or go-libp2p or whatever. it might even be worth putting in one of the ipfs projects instead of here since that would be more accurate to the dependency direction, but either way is fine.

**Comment by lgierth** [comment]
In fact this would be great to incorporate into the existing `/onion` transport :) https://github.com/openbazaar/go-onion-transport

**Comment by cretz** [comment]
Just a note, I did a PoC of a [transport](https://github.com/cretz/tor-dht-poc/blob/90b8daef09e95720d580851feb7389f416d2099b/go-tor-dht-poc/tordht/ipfs/transport.go) which uses v3 addresses (listen calls are much quicker) which required that I change the [protocol at runtime](https://github.com/cretz/tor-dht-poc/blob/90b8daef09e95720d580851feb7389f416d2099b/go-tor-dht-poc/tordht/ipfs/protocol.go). I have an issue in at https://github.com/multiformats/multiaddr/issues/65 to fix that.

Due to IPFS's volatility on interfaces like transport (notice how [Dial](https://godoc.org/github.com/libp2p/go-libp2p-transport#Transport) takes a context now) and invalid `/onion` multiaddr, it has solidified my reasoning that any integration with IPFS should be external to this repo.

**Comment by cretz** [comment]
I am closing this as it is not related to this library specifically. While I agree an IPFS onion transport based on this has value (and I even implemented one), it deserves to be done elsewhere instead of in this repo directly. Leaving comments open of course.

**Comment by bigs** [comment]
sounds good, thanks!
