### ISSUE TITLE
Persistence of onion id by the private key

### ISSUE THREAD

**Issue by MarinX** [cretz/bine#10]
How to persist an onion ID from a generated private key?

Key is generated by Shallot and imported:
```go
buff, _ := ioutil.ReadFile("mytor/private_key")
block, _ := pem.Decode(buff)
key, _ = x509.ParsePKCS1PrivateKey(block.Bytes)
cfg := &tor.ListenConf{
                 Key: key,
}
```

But onion id always change on each restart.

**Comment by cretz** [comment]
Are you sure that `ParsePKCS1PrivateKey` isn't erroring and the `key` isn't `nil`? I had tested this before without any issues and it is of course the same onion ID each time. If `key` is not nil and it's still not behaving as we expect, I'll write a onion v2 provided-key-same-onion-ID test to confirm.

**Comment by MarinX** [comment]
My bad...I override my private_key on each app start.
I generated a new one and its working fine!

Going to add a test as well, since I did not find anything related in tests.

**Comment by cretz** [comment]
@MarinX - What will the test do exactly? https://github.com/cretz/bine/blob/master/tests/tor_listen_test.go would probably be where it'd go, and I'd presume you'd have a hardcoded key in there and confirm the onion ID is returned if you want. I don't really have large coverage on these tests because they take a while to run (especially onion v2 service registration which is pretty slow).

**Comment by MarinX** [comment]
The test will import the key that is generated via Shallot ( so we know the onion ID ) and after the service is started, it will check if the onion id is a match.

There is no specification on how to import a key nor a test that shows usage, so I think its good to have it.

I agree about v2 :( pretty slow on bootstrapping

**Comment by cretz** [comment]
Another way to know the onion ID of a key, use the utils at https://godoc.org/github.com/cretz/bine/torutil
