### ISSUE TITLE
Ability to poll ListenService status or wait later

### ISSUE THREAD

**Issue by dballard** [cretz/bine#21]
We often spin up multiple onions at one time 
(in app, when loading multiple identities at once, in integ test. again, 1 server and 3 peers are created at once)
currently there is only support for waiting for full online status inline, at creation time with the call to Listen.
It would be nice if that code was pulled out and made an callable function, so we could init N onions, and then wait on all of them at once.

I'm not sure if there's anyway to make this a status like tors GetInfo of bootstrap startup phase, but that might be even more ideal, because our end goal is a GUI that just updates status icons of different parts, such as each Identity's coming online status. This may not be possible, that's fine

**Comment by cretz** [comment]
You can add an event listener that listens to that upload status, and set `NoWait` on `ListenConf` for all of the onion services, then enable network of you haven't, then check the events at the end using similar code to `Listen` for those upload statuses. 

I can break some of that code out, it's only a dozen or so lines. I personally wish there was a better way to know when uploaded. Also, in retrospect, I wonder if I should add the event handler before attempting to enable network to fix a potential race condition in cases where the network is already enabled and I miss events querying the network state...yeah, I should do that. Which means breaking out that code may be a bit more difficult since it will surround enabling the network. I'll do some thinking on this...

**Comment by cretz** [comment]
@dballard - After reviewing, I'm not sure I want to expose this logic as a supported feature because I don't believe it will forever be the best way to wait for an onion service to be published. So I suggest just using `NoWait` in the conf and then following the logic at https://github.com/cretz/bine/blob/465b9654846734321a5e1b3ee175474da377d0d6/tor/listen.go#L257-L286 but checking the service IDs you are waiting for. As for my potential race condition, while I am still concerned about an already enabled network, I'm not going to handle it.

Does that sound ok to just copy/reuse that simple logic? I just don't want to support it if exposed as a utility. Technically I could have a `MultiListen` but I fear the rarity need outweighs the benefits.

**Comment by dballard** [comment]
esh this has been open too long, sorry, I dont believe this is an issue for as any longer anyways
