### ISSUE TITLE
Webrtc transport

### ISSUE THREAD

**Issue by gedw99** [cretz/bine#3]
I saw a golang based implementation by the Tor team for webrtc.
Do you think it's on your roadmap ? 
I saw that it was a big effort by them..

**Comment by cretz** [comment]
Can you provide a link to the news and/or repo for the Go WebRTC implementation? I would find it interesting.

As for Tor, I've always figured it could be a WebRTC transport since it works behind NAT (obviating the need for a stun/turn server) and has a directory (obviating the need for a signalling server). However that would mostly only have value if implemented in the client (i.e. essentially only the browser).

As for this lib, it should be really easy to use with the Go paradigms of dial and listen. To keep the library general purpose I probably won't put any other not-directly-related pieces in here, but it could be done in another project.

**Comment by gedw99** [comment]
SO this is the original one:
https://github.com/keroserene/go-webrtc

But i think that got forked and maybe this is it:
https://gitweb.torproject.org/pluggable-transports/snowflake.git/

sorry but this is about all i know..

**Comment by gedw99** [comment]
https://gitweb.torproject.org/pluggable-transports/snowflake.git/tree/server-webrtc/snowflake.go

ah its wrapping the keroserene package it seems.

**Comment by cretz** [comment]
Ah yes, I have seen that one. Bine allows anyone to build transports for things, but I don't think I'll be building it or including it here in this repository. I'll keep comments open for discussion though.
