### ISSUE TITLE
Hide the tor dos window on windows

### ISSUE THREAD

**Issue by dballard** [cretz/bine#33]
PR #32 is to address this.

On Windows when Bine is starting Tor it creates a permanent dos console window. This PR mostly hides it (there is a brief blink into existence for it and then it's hidden). Looks a lot nicer and other OSs like Linux do not have this issue of a terminal being opened for a Tor process

**Comment by cretz** [comment]
Does it also create this window when starting from cmd or only via GUI situations (I personally haven't experienced it in my CLI apps)? Also, is this Tor version specific? What is the harm of this on existing CLI apps? Finally, I would like to make this opt-in, so maybe a `type CmdCreatorFunc func(ctx context.Context, exePath string, args ...string) (*exec.Cmd, error)` that implements `Creator` so that people can create the command any way they want instead of just this specific change.

**Comment by lu4p** [comment]
You may need to compile your code with `go build -ldflags '-H windowsgui'` which should hide any such windows.

**Comment by dballard** [comment]
haha thanks @lu4p but that did the opposite of what I needed. It hide my app's window but the tor dos console still popped up :)
I'll try these fixes certz has suggested just as soon as I can get building on windows working for me (unrelated toolchain problem  https://github.com/therecipe/qt/issues/909)

**Comment by blakeyi** [comment]
![image](https://user-images.githubusercontent.com/20620315/150481670-58d38c04-74ae-4a1f-b041-55dcb9292cb1.png)
