### ISSUE TITLE
chromedp?

### ISSUE THREAD

**Issue by r3k2** [cretz/bine#51]
Hello, any good way/example in how to plug chromedp to this?

Thanks

**Comment by cretz** [comment]
Sorry, just now getting back to this project. I do not have such an example. What specifically are you trying to do with chromedp over Tor?

chromedp like puppeteer and other chrome drivers works with Chrome remote protocol specifically, so you cannot drive the Tor browser with it of course.

If you are trying to access onion services or otherwise use Tor over Chrome, you can probably tell Chrome to use the Tor SOCKS proxy (though you lose some of the anonymity-preserving features of TBB).

If you are trying to communicate with a remote Chrome browser over Tor, this should not be too hard. On one side you'd have to start Chrome headlessly with a local port, then you can either create a simple proxy to tunnel bytes back and forth via a simple onion service (i.e. via `Tor.Listen`) or create a onion service directly linked to that chrome port using `Tor.Control.AddOnion` (see the source of `Tor.Listen` for how it does it for an explicitly created listener).

**Comment by cretz** [comment]
Closing...feel free to comment and/or request reopen.
